In [13]:
import numpy as np

In [14]:
# np.array()

a = np.array([43, 56, 35, 3])  #array
print(a)

b = [43, 56, 35,  3]  #List
print(b)

c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])   #array
print(c)

[43 56 35  3]
[43, 56, 35, 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [15]:
# np.ones

d = np.ones((2, 2))
print(d)

d = np.zeros((2, 2))
print(d)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]

In [16]:
# np.linspace

e = np.linspace(0, 5, 3)  #(start, stop, num)
print(e)

e = np.linspace(0, 5, 4)  #(start, stop, num)
print(e)

[0.  2.5 5. ]
[0.         1.66666667 3.33333333 5.        ]

In [19]:
# Attributes 

print (c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int64

In [21]:
# Accessing Arrays

print(c)
print(c[2][2])  #Go from first row to last row (because row =0,1,2) and column =0,1,2)
print(c[2,2])   #Same thing
print(c[1])    #second row
print(c[:,1])  #all the numbers in the second colunm

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
9
[4 5 6]
[2 5 8]

In [28]:
# Array Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(a + 1)
print(a * 2)
print(a * b)   # NOTE: ALWAYS MAKE SURE THEY ARE IN THE SAME SHAPE

# np.array_equal()
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print(a == b)
print(a > b)
print(np.array_equal(a, b))

[1 2 3]
[2 3 4]
[2 4 6]
[ 4 10 18]
[False  True False  True]
[False False  True False]
False

In [31]:
# Transpose and Reshape

a = np.array([[1, 1],
       [0, 0]])
print(a.T)
print(a.reshape((4,1)))
print(a.reshape((1,4)))

[[1 0]
 [1 0]]
[[1]
 [1]
 [0]
 [0]]
[[1 1 0 0]]

In [33]:
#Complex Operations
x = np.array([1, 3, 2])
print(x.sum())

print(x.min())
print(x.max())
print(x.mean())
print(np.median(x))
print(x.std())

6
1
3
2.0
2.0
0.816496580927726

In [34]:
# Reduction of rows and columns

a = np.array([[1, 1],
       [2, 2]])
print(a.sum(axis=0))  # adding rows
print(a.sum(axis=1))  # adding columns

[3 3]
[2 4]

In [35]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
print(np.dot(x, y))   # Dot product
print(np.cross(x, y)) # Cross product

a = np.array([[1, 1],
       [2, 2]])
b = np.array([[1, 3],
       [2, 4]])
print(np.matmul(a,b))  # matrix multiplication

20
[-1  2 -1]
[[ 3  7]
 [ 6 14]]

INTRO TO PANDAS

In [36]:
import pandas as pd

In [37]:
# Series (it is treated as a 1D array, similar to a single column in a spreadsheet)

s = pd.Series([1, 2, 5, np.nan, 6, 8])
s

0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [38]:
# DataFrame (it is a 2D table, analogous to an entire spreadsheet)

df = pd.DataFrame(np.random.randn(6, 4), columns=['A', 'B', 'C', 'D'])
df

          A         B         C         D
0  0.069152 -1.140400  0.109925  0.085263
1 -0.564723 -0.454113 -0.447662  2.623588
2  0.306976 -0.882585 -0.368913  1.010751
3  0.659178 -0.007457 -0.885225  1.505125
4  0.569772 -0.775760 -0.504305 -1.068805
5  0.116442 -0.348976 -0.290647  0.952145

In [40]:
print(df.head)  #first couple of rows
print(df.tail(2))  #last couple of rows

<bound method NDFrame.head of           A         B         C         D
0  0.069152 -1.140400  0.109925  0.085263
1 -0.564723 -0.454113 -0.447662  2.623588
2  0.306976 -0.882585 -0.368913  1.010751
3  0.659178 -0.007457 -0.885225  1.505125
4  0.569772 -0.775760 -0.504305 -1.068805
5  0.116442 -0.348976 -0.290647  0.952145>
          A         B         C         D
4  0.569772 -0.775760 -0.504305 -1.068805
5  0.116442 -0.348976 -0.290647  0.952145

In [42]:
print(df.columns)
print(df['B'])

Index(['A', 'B', 'C', 'D'], dtype='str')
0   -1.140400
1   -0.454113
2   -0.882585
3   -0.007457
4   -0.775760
5   -0.348976
Name: B, dtype: float64

In [43]:
df[0:3]

          A         B         C         D
0  0.069152 -1.140400  0.109925  0.085263
1 -0.564723 -0.454113 -0.447662  2.623588
2  0.306976 -0.882585 -0.368913  1.010751

In [44]:
df[['A', 'B']]

          A         B
0  0.069152 -1.140400
1 -0.564723 -0.454113
2  0.306976 -0.882585
3  0.659178 -0.007457
4  0.569772 -0.775760
5  0.116442 -0.348976

In [45]:
df.iloc[0]   #for selecting a single row

A    0.069152
B   -1.140400
C    0.109925
D    0.085263
Name: 0, dtype: float64

In [46]:
df.iloc[0:3]

          A         B         C         D
0  0.069152 -1.140400  0.109925  0.085263
1 -0.564723 -0.454113 -0.447662  2.623588
2  0.306976 -0.882585 -0.368913  1.010751

In [47]:
df.iloc[0:3, 1:3]

          B         C
0 -1.140400  0.109925
1 -0.454113 -0.447662
2 -0.882585 -0.368913

In [57]:
# Editing data frame

s1 = pd.Series([1, 2, 3, 4, 5, 6])
print(s1)
df['F'] = s1 # This creates a new column 'F' equal to Series s1
print(df)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
          A         B         C         D  F
0  0.000000       NaN  0.109925  0.085263  1
1 -0.564723 -0.454113 -0.447662  2.623588  2
2  0.306976 -0.882585 -0.368913  1.010751  3
3  0.659178 -0.007457 -0.885225  1.505125  4
4  0.569772 -0.775760 -0.504305 -1.068805  5
5  0.116442 -0.348976 -0.290647  0.952145  6

In [58]:
df.at[0, 'A'] = 0  # The first 0 is the label, 'A' is the column
df.iat[0, 1] = np.nan
print(df)   #same thing wit the former cell

          A         B         C         D  F
0  0.000000       NaN  0.109925  0.085263  1
1 -0.564723 -0.454113 -0.447662  2.623588  2
2  0.306976 -0.882585 -0.368913  1.010751  3
3  0.659178 -0.007457 -0.885225  1.505125  4
4  0.569772 -0.775760 -0.504305 -1.068805  5
5  0.116442 -0.348976 -0.290647  0.952145  6

In [67]:
# Append or concat (i want to add an existing dataframe, we can only use conact because this is a new version)

df1 = pd.DataFrame(np.random.randn(3, 5), columns=['A', 'B', 'C', 'D', 'F'])

df = pd.concat([df, df1])
print(df)

          A         B         C         D         F
0  0.000000       NaN  0.109925  0.085263  1.000000
1 -0.564723 -0.454113 -0.447662  2.623588  2.000000
2  0.306976 -0.882585 -0.368913  1.010751  3.000000
3  0.659178 -0.007457 -0.885225  1.505125  4.000000
4  0.569772 -0.775760 -0.504305 -1.068805  5.000000
5  0.116442 -0.348976 -0.290647  0.952145  6.000000
0 -1.400154 -0.952446 -1.888898 -2.004763  0.206192
1  0.330413  1.385687  0.613919  0.777104  2.355620
2 -0.889276 -0.695312 -0.578907  0.447773 -1.002741

In [68]:
df = df.reset_index(drop=True)
df

          A         B         C         D         F
0  0.000000       NaN  0.109925  0.085263  1.000000
1 -0.564723 -0.454113 -0.447662  2.623588  2.000000
2  0.306976 -0.882585 -0.368913  1.010751  3.000000
3  0.659178 -0.007457 -0.885225  1.505125  4.000000
4  0.569772 -0.775760 -0.504305 -1.068805  5.000000
5  0.116442 -0.348976 -0.290647  0.952145  6.000000
6 -1.400154 -0.952446 -1.888898 -2.004763  0.206192
7  0.330413  1.385687  0.613919  0.777104  2.355620
8 -0.889276 -0.695312 -0.578907  0.447773 -1.002741

In [70]:
c1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9], name='Z')
df =pd.concat([df, c1], axis=1)
df

          A         B         C         D         F  Z
0  0.000000       NaN  0.109925  0.085263  1.000000  1
1 -0.564723 -0.454113 -0.447662  2.623588  2.000000  2
2  0.306976 -0.882585 -0.368913  1.010751  3.000000  3
3  0.659178 -0.007457 -0.885225  1.505125  4.000000  4
4  0.569772 -0.775760 -0.504305 -1.068805  5.000000  5
5  0.116442 -0.348976 -0.290647  0.952145  6.000000  6
6 -1.400154 -0.952446 -1.888898 -2.004763  0.206192  7
7  0.330413  1.385687  0.613919  0.777104  2.355620  8
8 -0.889276 -0.695312 -0.578907  0.447773 -1.002741  9